version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'icetradebot.tk -> http://web:3000'
      STAGE: 'production'
    restart: always
    depends_on:
      - web
  web:
    build:
      context: .
    image: "icetrade-bot"
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    env_file: .env
    environment:
      RAILS_ENV: production
    restart: always
    depends_on:
      - db
    tty: true
    stdin_open: true
  poller:
    image: "icetrade-bot"
    command: /bin/bash -c "bin/delayed_job start && bin/rails telegram:bot:poller"
    env_file: .env
    environment:
      RAILS_ENV: production
    restart: always
    depends_on:
      - db
  db:
    image: postgres:11.7-alpine
    env_file: .env
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
