version: '3'
services:
  web:
    build:
      context: .
    image: "deluxe:one-ingest"
    command: /bin/bash -c "bin/rails telegram:bot:poller && bin/delayed_job start"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

  db:
    image: postgres:11.7-alpine
    env_file: .env
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
