version: '3'
services:
  web:
    build:
      context: .
    image: "deluxe:one-ingest"
    # command: /bin/bash -c "bin/rails telegram:bot:poller && bin/delayed_job start"
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid && bin/delayed_job start"
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

  db:
    image: postgres:11.7-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
